### ISSUE TITLE
Code redundancy in `pipeline.vote`

### ISSUE THREAD

**Issue by CsterKuroi** [bigchaindb/bigchaindb#1005]
Open `models.py` and `pipeline.vote.py`
```
    vote_pipeline = Pipeline([
        Node(voter.validate_block),
        Node(voter.ungroup),
        Node(voter.validate_tx, fraction_of_cores=1),
        Node(voter.vote),
        Node(voter.write_vote)
    ])
```
1. `voter.validate_block` cotains `self.consensus.validate_block(self.bigchain, block)` ,and it calls Class Block method `validate(self, bigchain)` in `models.py:184`, in this method
```
        for tx in self.transactions:
            # NOTE: If a transaction is not valid, `is_valid` will throw an
            #       an exception and block validation will be canceled.
            bigchain.validate_transaction(tx)
```
So in `voter.validate_block` we validate all of the txs ,then in `voter.validate_tx` we validate all of the txs again.Whether it affects efficiency? **Is it necessary to validate all of the txs in `Block.validate()`?**

2. in `pipeline.vote.py:48`
```
         if not self.bigchain.has_previous_vote(block['id'],
                                               block['block']['voters']):
```
in `models:202`
```
        if bigchain.has_previous_vote(self.id, self.voters):
```
in `voter.validate_block` we would do `bigchain.has_previous_vote` twice.**Is it necessary to make sure has_previous_vote in `Block.validate()`?**

3.  in `models.py:256`  of `from_dict(cls, block_body)` , Target is to transform a Python dictionary to a Block object. But:

```
        if block_id != block_body['id']:
            raise InvalidHash()
```

```
        if signature is not None:
            # NOTE: CC throws a `ValueError` on some wrong signatures
            #       https://github.com/bigchaindb/cryptoconditions/issues/27
            try:
                signature_valid = public_key\
                        .verify(block_serialized.encode(), signature)
            except ValueError:
                signature_valid = False
            if signature_valid is False:
                raise InvalidSignature('Invalid block signature')

```
**Is it necessary to verify Signature and blockhash in method `from_dict()`? And in `models.py:210` of method `validate(self, bigchain)`** 

```
        if not self.is_signature_valid():
            raise InvalidSignature('Block signature invalid')
```
verify Signature again..

**Comment by CsterKuroi** [comment]
Sorry, typesetting and English are not very good...

**Comment by sbellem** [comment]
Hi @CsterKuroi, thanks for raising this issue! We'll look into it as soon as possible!

/cc @r-marques

**Comment by r-marques** [comment]
@CsterKuroi you are right.

I created issues to address different points that you mentioned:
- [ ] 1. will be addressed in #1132 
- [ ] 2. is already being addressed in #1130 
- [ ] 3. will be addressed in #1133

I will leave this issue open until all other issues are resolved

**Comment by r-marques** [comment]
I will close this since all the issues have been resolved.

One thing to note about 3. is that we still do the `id` validation on the `from_dict`. The reason for this is that its only place where we have access to the actual json payload. After that `Block.id` is just a property that is dynamically calculated every time its called.
