### ISSUE TITLE
Support MongoDB replication

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#1054]
The goal of this project is to add BigchainDB support for MongoDB replication.

#### Configuring Replication
Replication with MongoDB works quite differently from RethinkDB.
With RethinkDB the way it works is:
1. We configure all the nodes with the cluster information (hostname and ports of all the nodes in the cluster)
2. Start the nodes. At this point all the nodes connect between themselves, although we have not configured any replication yet.
3. We can change replication configuration. The replication is set per table.

With MongoDB the way it works is:
1.  first we start the node(s) with the replica set option enabled. At this point the nodes are not connected to each other and the replication is still not enabled
2.  Initialize the replica set and give it a replica set name. This needs to be done only once. During this step we can also specify all other nodes in the cluster.
3. Unlike RethinkDB we do not set the number of replicas we want, instead we add or remove nodes from the replica set and replication will be applied to all collections in the database.

#### Client Drivers
Again the default behaviour of the MongoDB client drivers or at least pymongo is quite different from RethinkDB.

With RethinkDB we would connect to a single node, any node (our default behaviour would be to connect to our local instance) and RethinkDB would take care of forwarding the queries to the relevant node(s)

With MongoDB a driver should not connect to a single node, instead they should connect to a replica set. This brings high availability to the driver, meaning that if the node that we are connected to (usually the primary) goes down, the driver will automatically reconnect to the new primary when it becomes available. Moreover if we were to connect to a single node and if that node was a secondary, since MongoDB nodes do not forward client queries, we would not be able to write because secondary are not allowed to write, and read queries would depend on the read concern.

So when setting up client driver connection we still need to specify a node to connect to and a replica set name. The driver will then connect to that node, retrieve information about the nodes in the replica set and reconnect with the primary.

#### References
- MongoDB [Replication](https://docs.mongodb.com/manual/replication/) and [Replica Set Tutorials](https://docs.mongodb.com/manual/administration/replica-set-deployment/)
- [High Availability and Pymongo](http://api.mongodb.com/python/current/examples/high_availability.html)
- [MongoDB Drivers And High Availability: Deep Dive](https://www.mongodb.com/presentations/mongodb-drivers-and-high-availability-deep-dive) and [blog](https://emptysqua.re/blog/server-discovery-and-monitoring-in-mongodb-drivers/)
- [mtools](https://github.com/rueckstiess/mtools) easily setup and manage mongodb test environments

#### Issues
- [x] Add bigchaindb commands for adding, removing nodes from the replica set. #1055
- [x] the cluster needs to know the replica set name and so does the driver. Add it to the configuration file. Update driver initialization. #1056
- [x] Handle driver reconnect. Driver already reconnects but we may need to still catch AutoReconnect exceptions. #975
- [x] Add mongodb support for `bigchaindb configure` in both interactive and non-interactive mode `-y` #1057
- [x] Deployment scripts for aws/azure and docker files #1058
- [x] Documentation #1059

Am I missing something? Or is this enough at least for our development deployments (docker, aws/azure scripts)
