### ISSUE TITLE
Multiple fulfillments for the same condition leads to double spends

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#1099]
From @jmduque on gitter:

> We can created a transaction using the same condition twice for a divisible asset and we were successfully able to create an output where the total amount was expected to be the sum of both inputs and consequently created money!

> last condition:

![blob](https://cloud.githubusercontent.com/assets/1793187/22325000/7863c748-e3ac-11e6-9904-2b3d412e0321.png)

> fullfilments for next transaction:
> notice both fulfillment's reference same transaction and same cid

![blob](https://cloud.githubusercontent.com/assets/1793187/22325021/912e63c8-e3ac-11e6-8d1d-ee67645a0f58.png)

> Output Conditions (notice they are double the amount of latest condition):

![blob](https://cloud.githubusercontent.com/assets/1793187/22325035/a6355ab0-e3ac-11e6-94be-de32eecd7c39.png)

#### Todo:
- [ ] Recreate the bug
- [ ] Fix it
- [ ] Incorporate the changes into 0.8.1 and do hotfix release 0.8.2
- [ ] Incorporate the changes into master

**Comment by libscott** [comment]
@jmduque Thanks for reporting this

**Comment by jmduque** [comment]
Thanks for the quick turn-around!
