### ISSUE TITLE
Support for divisible assets

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#129]
relates to #128 #99 #125 

The ability to divide assets is common in crypto currency ledgers but its difficult to envision on a digital asset ledger where there is no notion of value or amount.

There are use cases where this may be desirable:
- Building a crypto currency with BigchainDB
- Track the supply chain of physical goods. A raw material that is transformed at some point in the supply chain.

I propose that we define a generic template for digital assets that would have a field that specifies if the digital asset is divisible or not and add a pluggable consensus rule to and the case of divisible assets. The consensus rule should extend the core consensus instead of completely overriding it.

A generic divisible asset should provide:
- Value
- Minimum divisible unit eg 1/10^8

The consensus rules need to:
- Respect the minimum divisible unit
- Enforce the conservation law. The sum of all the parts should never with greater then the initial value.

**TODO**:
- [x] Define digital asset #125 
- [x] Implement digital asset template #564
- [x] Document digital asset template #566 
- [x] Implement divisible assets #488 
- [x] Documentation and examples for divisible assets #486

**Comment by TimDaub** [comment]
I think I'm in line with what was proposed here.

What I'd like to have is define on the creation of a digital asset is it's divisibility.
The use case for this is simple:

You want to enable users to create artificially limited assets (essentially "limited editions").
In that case, you'd only be able to divide and "spend" the asset by the number of times it was defined in its registration. In turn this allows economics where a digital asset is only spendable in a limited quantity to gain actual value.

**Comment by r-marques** [comment]
The simplest way to go about it would be to assume that the minimum divisible unit is always `1`. And in the definition of the digital asset you specify an amount. For example if you create a divisible digital asset with `amount=10` this means that there will be at most 10 shares of that digital asset.

**Comment by lucidfrontier45** [comment]
Hi guys.

Any updates on this issue? I want to make a bitcoin like financial system with numeric payload and I think divisible asset is necessary for this usage.

**Comment by ttmc** [comment]
Support for divisible assets is not currently a high priority for us. If you want to make a "bitcoin like financial system" then why not use one of the existing cryptocurrencies?

**Comment by furiousOyster** [comment]
@ttmc because transactional thruput !  bigchaindb holds great promise in tx/sec and we, the naive onlookers, feel that a numeric payload would be easy* and super beneficial.

**Comment by ttmc** [comment]
@furiousOyster We _do_ plan to support divisible assets eventually. It's on our [roadmap](https://github.com/bigchaindb/org/blob/master/ROADMAP.md).

**Comment by lucidfrontier45** [comment]
@ttmc 

My motivations to use BigchainDB are

1. It uses RethinkDB and highly scalable
2. It is built with Python and easy for me to use its server API and build application.

I think divisible asset or numeric payload support is a key feature to build EC like system.
I just want to know how the priority of this issue and how soon it will be implemented.

**Comment by r-marques** [comment]
We are having a planning session tomorrow so we should have have an update about this feature then.

**Comment by ttmc** [comment]
In today's planning session, we bumped this issue to "In progress." That is, we're now actively working on it.

**Comment by lucidfrontier45** [comment]
Good to hear that!

**Comment by r-marques** [comment]
Initial specs for divisible assets #487 
If anyone would like comment or provide suggestions

cc @diminator

**Comment by TimDaub** [comment]
@lucidfrontier45 We've merged the PR for divisible assets support (#794).
We're currently working on including them in the HTTP API and driver.

Let me know if you have further questions.

**Comment by r-marques** [comment]
Finished with https://github.com/bigchaindb/bigchaindb-driver/pull/166
