### ISSUE TITLE
Using/ignoring the value of "version" in transactions for BDB Server version 1.0.0+

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1558]
[The BigchainDB transaction model](https://docs.bigchaindb.com/projects/server/en/latest/data-models/transaction-model.html) contains a top-level key-value pair:
```json
    "version": "<version number of the transaction model>",
```

What values are allowed for "version"? The schema file at `bigchaindb/bigchaindb/common/schema/transaction.yaml` contains:
```yaml
  version:
    type: string
    pattern: "^0\\."
    description: |
        BigchainDB transaction schema version.
```

What will happen if someone puts "1.0" as the value for "version"?

Is the value of the "version" used by BigchainDB Server anywhere today, or is it just ignored?

If someone puts "2.0" as the value of "version" today (or with BigchainDB Server 1.0.0), will that value be ignored, so that their transaction might be considered valid today, but in the future, it won't be considered valid, once there is an actual version 2 of the transaction schema/model?

Maybe BigchainDB Server should explicitly require that the value of "version" be "1.0" starting with BigchainDB Server version 1.0.0?

**Comment by ttmc** [comment]
Note: It looks like we'll be calling the version 1.0.0 release candidate version `1.0.0rc1` to comply with [the Python way of doing semantic versioning](https://packaging.python.org/tutorials/distributing-packages/#choosing-a-versioning-scheme) (which agrees with [regular Semantic Versioning](http://semver.org/) except there's no hyphen between the 1.0.0 and the rc1, i.e. not `1.0.0-rc1`).

We need to make sure that won't break something, because we've never had a version name that looked like that before. For example, we've had `0.11.0.dev` not `0.11.0dev`.

**Comment by libscott** [comment]
> Maybe BigchainDB Server should explicitly require that the value of "version" be "1.0" starting with BigchainDB Server version 1.0.0?

Yes, that's the idea. After 1.0, transaction model version will break step with server version.

**Comment by TimDaub** [comment]
A quick task check list:

- [ ] Adjust javascript driver
- [ ] Adjust python driver
- [ ] Adjust CLI
- [x] Make change in BDB server #1574
- [ ] Add to changelog in #1561
- [ ] Add to upgrade-guide in #1547

**Comment by ttmc** [comment]
The change has now been made to the BigchainDB Server code (via PR #1574), and the changelog was updated too (in PR #1561). Therefore I think we can now release BigchainDB Server version 1.0.0rc1. The other stuff can be done after that.

**Comment by krish7919** [comment]
@libscott Can we close this?

**Comment by TimDaub** [comment]
> @libscott Can we close this?

No, see: https://github.com/bigchaindb/bigchaindb/issues/1558#issuecomment-310317072

**Comment by TimDaub** [comment]
> If possible, lets do one release of the CLI ie once all TX interface changes are merged.

Because all changes relate to edits made in `bigchaindb.common`?
Sounds good.
