### ISSUE TITLE
Update high-level docs re/ revised tx model, revised crypto-conditions, etc.

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1585]
- [x] Transaction Model page: #1586
- [x] Inputs and Outputs page: #1573 
- [x] All relevant root docs: #1571

**Comment by ttmc** [comment]
All steps are done so I can close this issue now.
