### ISSUE TITLE
AWS Marketplace Listing TODO

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#173]
This is a list of the things we need to do before AWS Marketplace will accept the BigchainDB AMI & documentation for listing.

Note:  We can send the AMI to our AWS contacts for review: see emails from them. We can also get a listing in a "test mode" so that we can see how it will look on the AWS Marketplace before we make it visible to the public.
- [ ] Complete the checklist on page 2 of the AWS Marketplace Seller Guide (Amazon.com Confidential; ask Troy if you want a copy). A big part of that is item 1: "Production-ready" (i.e. "not in Beta")
- [ ] High-availability. What happens if a node crashes?
- [ ] Backup & restore capabilities and documentation, including a way to take regular snapshots
- [ ] Documentation about common use cases and user stories
- [ ] Documentation explaining the why and how of the federation model, how to start a new federation, how to join a federation

**Comment by sohkai** [comment]
@ttmc Maybe we should close this for now?

**Comment by ttmc** [comment]
@sohkai This _is_ an old issue, but I think it's still something we may do some day.

**Comment by ttmc** [comment]
Our recommended BigchainDB Node deployment strategy has changed a lot since this issue was created so I'm closing it.
