### ISSUE TITLE
Project Escrow

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#201]
# Abstract
Escrowing assets means that they are locked up until an unlocking condition is fulfilled.

# Motivation

Escrow enables us to integrate in the ILP platform and unlocks many other neat usecases.

# Background
## Example
User `A` might want to send an asset to user `B`, but the actual transaction can only go through if user `B` fulfills a certain condition (e.g. provide a proof of payment or a signed receipt) before a timeout occurs.

Once the proof is provided before timeout, then the asset is sent to user `B`. If the timeout occurs, the escrow is aborted and the asset flows back to user `A`.

```
                      execute
    escrow           --------> B
A ---------> [A, B] /
                    \
                     --------> A
                       abort
```

## Interledger connection
Ledger-provided escrow is a requirement for the Interledger Protocol (ILP):
![image](https://cloud.githubusercontent.com/assets/6178597/14678983/467fe17e-0718-11e6-8998-8fbc14753cde.png)

In this setup, the connector is user `B` and will pass the receipt (`execute` fulfillment) of another ledger to the escrow transaction in order to redeem the funds. The abort transaction is implemented as a timeout.

# Implementations

When placing an asset in escrow, one should provide 2 output-conditions: an `execute` and `abort` condition.

## Execute condition

once the escrow condition is fulfilled before timeout, the assert transfers to user `B`

```          
    escrow           execute
A ---------> [A, B] --------> B
```

## Abort condition

When the escrow times out or another abort fulfillment is provided, one of the following scenario's can occur:

- the asset is transfered to user `A`
```          
    escrow            abort
A ---------> [A, B] --------> A
```

- Validators ignore the escrow transaction and user `B` cannot redeem the output condition
```          
    escrow            abort
A ---------> [A, B] ---x----> B
   \
    ------------------------> A
```
- other possiblilities ...WIP

## Timeout

A typical abort condition for escrow is a timeout meaning that the abort condition will automatically be regarded as fulfilled once the timeout has occured.

This timeout shouldnt be checked in realtime using polling or so, but only when:
- `A` or `B` tries to fulfill the `execute` or  `abort` escrow transaction respectively
- `A` tries to spend the original asset that was placed in escrow

## Fulfillment

The escrow fulfillment for the `execute` condition can be signed by any party:
- any user on the bigchaindb ledger
- any user of an external ledger, connected by interledger
- anonymous as for regular hash-locks where the fulfillment is a `preimage` and the condition is `sha256(preimage)`

## Tasks

- [ ] support both `execute` and `abort` condition: a single-input transaction (with 1 fulfillment) should support two output conditions
- [ ] after the `execute` condition, user `A` is not anymore an owner of the asset
- [ ] after the `abort` condition, user `B` is not anymore an owner of the asset
- [ ] validator nodes recognize escrow transfers
- [ ] implement timout as a condition and account for during validation

## Resources

- [Multisig escrow on bitcoin](https://en.bitcoin.it/wiki/Multisignature) requires a 3th party (so not ledger-provided)
- bitcoin escrow [without 3th party](https://people.xiph.org/~greg/escrowexample.txt), also [here](https://bitcoin.org/en/developer-guide#escrow-and-arbitration)
- bitcoin [cross-chain trading](https://en.bitcoin.it/wiki/Atomic_cross-chain_trading), also [here](http://upcoder.com/11/atomic-cross-chain-exchange/)
- ...

**Comment by r-marques** [comment]
Assuming that there exists a timeout condition I think that the simplest workflow would be:
```          
    escrow            abort
A ---------> B ---x----> B
   \
    ------------------------> A
```

Flow:
1. `A` owns `asset1`
2. `A` creates a transfer transaction to `B` with a custom timeout condition
3. At this point neither `A` nor `B` own `asset1`.
4. Before timeout:
    4.1 `A` tries to spend `asset1` again and this results in a double spend (although `B` hasn't fulfilled the condition, the timeout hasn't occurred.
    4.2 `B` fulfills the condition by creating a transaction transferring `asset1` back to itself
    4.3 `B` now owns `asset1`
5. After timeout:
    5.1 `B` tries to fulfill the condition but it fails because the timeout already occurred.
    5.2 `A` tries to spend `asset1` but now it is not flagged as a double spend because although it was already used, it was in a transaction with a timeout condition that was never fulfilled (and thus considered invalid in this escrow flow).
