### ISSUE TITLE
BEP#3 "Dynamically add/remove validators at runtime (Insecure version)" implementation

### ISSUE THREAD

**Issue by kansi** [bigchaindb/bigchaindb#2098]
### TODOs

- [x] Add sub-command `upsert-validator`  #2070
- [x] Add api `GET /api/v1/validators`  #2106
- [x] Add documentation for the above features. #2123

### Related issues
- #1989

**Comment by kansi** [comment]
PRs merged
