### ISSUE TITLE
Transaction expiry condition

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#262]
Part of Escrow issue #201 

# Abstract

A transaction with an `expiry datetime` can only be fulfilled before the timeout occurs.
Related is the `lock_time` of [delayed bitcoin transactions](https://bitcointalk.org/index.php?topic=131443.0),  ie transaction can only be fulfilled after `lock_time`
 
# Tasks

- [ ] decide to go for `expires_at` or `lock_time`
- [ ] Add field to transaction block, defaults to `None`
- [ ] Make sure the time is set relative to the transaction time (first seen in `bigchain` or `backlog`)
- [ ] Add time condition/fulfillment to `validate_transaction` logic
