### ISSUE TITLE
All known fault vectors accounted for, w/ system test per fault

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#284]
# Abstract

BigchainDB is built on RethinkDB / MongoDB, which is tolerant to (most) crash faults but not malicious faults. The aim of this project is to identify all fault vectors, identify which ones really matter in practical scenarios, then engineer solutions for them. 
# Motivation

For production usage, BigchainDB needs to be resilient to all crash and malicious faults (within reason, i.e. that have high impact if they happen and high probability of happening).
# Goals
- Identify & document faults
- For each fault: 
  - Write a system test to expose it
  - Design & implement a solution that passes the test
# Challenges
- Backend DB has no notion of a federation; we have to add that somehow
- We won't be able to be 100% thorough so this project will be followed by a 3rd party security audit (#292)
# Tools to help / ideas

(WIP - spread across many places)
- Changefeed to catch deletes, etc. (Note added later: this doesn't work, because during the window when the block or whatever is gone from RethinkDB, otherwise invalid transactions [such as double spends] might be valid. The only solution is to prevent deletes [and similar bad things] before they happen.)
- Snapshotting / continuous backups (#283) 
- Make backend DB require signatures?
- Use a firewall or intrusion detection system that inspects IP packets, checks backend DB wire protocol messages, and block certain actions at that level. Note: this is a big project and got its own issue: #594
# Tasks

(label == topic: SEC core consensus) and (label != Project-Issue) and (not already in Project Issue #199)
- [ ] Issue #703 - Block requests to elect a new Raft leader when a leader is currently active
- [ ] Issue #524 - Revisit how invalid tx get decided invalid and actions taken
- [ ] Issue #483 - Mitigate malicious nodes tampering with the changefeeds where they contribute
- [ ] Issue #474 - Blocks might go undecided forever
- [ ] Issue #444 - What to do when a node creates another Genesis block?
- [x] Issue #424 - Handle the Case of the Unlucky Valid Transaction. Closed: wontfix
- [ ] Issue #354 - Notify other nodes when Byzantine behavior is detected
- [ ] Issue #353 - Compromised node with primary replica of a shard lies and says it doesn't have it
- [ ] Issue #352 - Fault: Atomicity of multiple updates/deletes is not guaranteed
- [ ] Issue #351 - Handle the case of several nodes disagreeing on the validity of a block
- [ ] Issue #350 - Handle blocks that have been undecided for too long
- [x] Issue #346 - Compromised node ruining blocks by including 1+ invalid tx in blocks it builds
- [ ] Issue #345 - Handle transaction reordering attacks
- [ ] Issue #344 - Prevent replay attacks?
- [x] Issue #339 - Transaction malleability of transactions containing no signatures
- [x] Issue #338 - Handle the case of a faulty node saying that an invalid tx is valid? Closed because Issue #354 covers it.
- [x] Issue #336 - Handle case of faulty node dropping just-received transactions
- [x] Issue #335 - Denial-of-service attack from clients: mitigations & defenses
- [x] Issue #327 - Add assurances that a node can't modify the payload in a CREATE transaction
- [x] Issue #251 - Bigchain.write_transaction changes the transaction passed as argument
- [x] Issue #240 - How to lock down the RethinkDB "admin" account?
- [x] Issue #238 - Inconsistency between vote and transaction signing
- [ ] Issue #189 - Secure management of private keys
- [x] Issue #132 - Revisit timestamps?
- [ ] Issue #77 - Secure node-to-node communications
- [ ] Issue #20 - Non Deterministic assignment of transactions in S is a DoS vulnerability

**Comment by sohkai** [comment]
@ttmc I think we should create a milestone around this to group things, and this can be the milestone header issue (since milestones themselves really suck at presenting info).

**Comment by ttmc** [comment]
We don't really use milestones. "Project" issues with check-boxed lists of issues already have a nice UI on GitHub, with an auto-generated "3 out of 11" progress bar etc.

**Comment by sohkai** [comment]
The only thing I'm not particularly happy about with "Project" issues is that you have to keep updating the project issue if other issues are created after. It's kind of a pain to keep having to remember which issue to link it back to, and then making sure you add it there.

**Comment by ttmc** [comment]
I don't think it's so awful to remember the "Project" issue you're working on. It's on the wall in the conference room. If you can't get into the conference room to look, then GitHub also automatically says when two issues are linked via mentions.
