### ISSUE TITLE
Refactor BigchainDB code into different modules

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#312]
Right now the BigchainDB Python package puts together:
- the code to run a Node in the federation
- the code to talk to the Federation (aka the Driver)

This proposal is to split the BigchainDB module into three smaller modules:
- `bigchaindb-node`, containing the code to run a Node
- `bigchaindb-driver`, containing all the code a program needs to talk to the Federation
- `bigchaindb-lib` (or `bigchaindb-common`), the basic API, containing all the functions/classes to create, validate, and sign transactions
# Subtasks
- [x] port `block` to the new `pipeline` architecture #493 @vrde
- [x] port `voter` to the new `pipeline` architecture #494 @vrde @rhsimplex 
- [x] rename `current_owner` and `new_owner` #348 @TimDaub
- CLOSED redesign and refactor core functionalities #496 @vrde
- [x] ~~document multiprocessing @vrde~~ Documenting multipipes is outside the scope of this project
- [x] isolate transaction code #499 @TimDaub 
- [x] remove plugin architecture #500 @sbellem 
- [x] port `election` to the new `pipeline` architecture #495 @rhsimplex 
- CLOSED group consensus logic #501 @r-marques 
- [x] Isolate code to access the Database #502 @vrde 
- [x] Integrate new transaction model #586 @TimDaub
- [x] Align vote and transaction signing #238 @rhsimplex

**Comment by ttmc** [comment]
I wonder if it would make sense to further divide `bigchaindb-node` into at least two different executable programs:

1. A block-builder, vote-builder, etc.
2. A highly-specialized program that does just one thing: it gets transactions (e.g. putting them in its own queue), checks them for validity, and returns the results. The idea is to make transaction validation highly-scalable just by just adding more of these guys (maybe on separate machines). Each one might live inside its own container, with CPU and RAM requirements.

**Comment by sbellem** [comment]
Was licensing considered?

If the server code is AGPL, and we have a bunch of logic that is extracted out into a common repo, and this repo is not AGPL, is this ok?

Do we have an idea of what must stay in the AGPL repo because of licensing concerns?

**Comment by gmcmullen** [comment]
We hold the copyright in the code so we can license it however we want. 

If we want it to be part of BigchainDB as a commercial product it should be AGPL, even if it's AGPL-licensed under multiple repos.

**Comment by sbellem** [comment]
Thanks @gmcmullen

**Comment by sohkai** [comment]
Closing, as we've resolved most of the refactoring mentioned.
