### ISSUE TITLE
Deployment & Operations issues

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#331]
Tools and documentation to help with deployment and day-to-day operations of BigchainDB nodes and clusters/federations.

- [x] Initial documentation on federations - Issue #388 
- [x] New and revised timestamp docs (including notes on NTP daemon setup) - Issue #397
- [x] Initial docs on RethinkDB storage setup - Issue #416 
- [x] Initial docs on firewall setup - Issue #417 
- [x] Ability to deploy a cluster on AWS using EBS-only instances - Issue #461 and Pull Request #469 

Trent said this Project Issue was too general so it was split apart into more specific ones:

* Secure management of private keys (on nodes) - Issue #189
* Cluster Configuration Management system - Issue #436
* Production Node Deployment & Management - Issue #498
* More...

**Historical Notes**

This Project-Issue started out mixed up with benchmarking on the physical planning board (Project Minky, issue #246 and Project Norbert, issue #321). It got separated out into its own issue (this issue), which originally was just about _documenting_ how to set up and run a federation. Over time, it became clear that there were missing deployment tools, so creating those also became part of this issue. It's now a real "Project-Issue," linking to many sub-issues.

This issue also replaces issue #126 (Define how a federation is managed).

**Comment by ttmc** [comment]
This project includes issue #126 ("Define how a federation is managed").
