### ISSUE TITLE
Project: Changes to data models (mostly the transaction model)

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#342]
There are several (mostly small) changes to be made to the Bigchaindb [`transaction` model (data model)](http://bigchaindb.readthedocs.io/en/latest/models.html#the-transaction-model). This project is a collection of several such issues:
- [ ] Transaction malleability of transactions containing no signatures - Issue #339
- [x] Remove "operation" from transactions: not needed - Issue #340 - CLOSED / wontfix
- [ ] Remove "invalid_reason" from the vote model? Issue #217
- [x] Move "version" inside transaction body and include it in what gets hashed - Issue #341 - This _was_ done but then got undone. See:  Redo? Move "version" inside transaction body and include it in what gets hashed = issue #755
- [x] Revisit timestamps? Issue #132
- [x] Improve the security of CREATE transactions - Issue #347
- [x] Add assurances that a node can't modify the payload in a CREATE transaction - Issue #327 . Note that this issue may be resolved by what @diminator proposed in  Issue #347
- [x] Proposal on how to rename `current_owners` or `new_owners` (in fulfillments and conditions, respectively) - Issue #348

**Comment by ttmc** [comment]
@sohkai created a new GitHub milestone named [BigchainDB Transaction Model Upgrades](https://github.com/bigchaindb/bigchaindb/milestone/5). It does what this issue did, but is up-to-date, so I will close this issue.

Note: There's one issue here (#217) that's related to the vote model, but it can live quite happily by itself.
