### ISSUE TITLE
ILP-BDB demo: spk to other ledgers

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#360]
Demo connecting two ledgers via the Interledger Protocol. Aiming for July 6.
## sub-issues:
- [ ] : First cut implementation #489 
- [ ] : Connect frontend wallet #490
- [ ] : Connect BDB backend #491
