### ISSUE TITLE
Define Client-Server v1.1 API

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#362]
# Abstract
Improve the BigchainDB client-server API.

# Goals
Currently BigchainDB has a simple HTTP REST API with two endpoints but it should be revisited and improved. ~~We may want a websocket API instead or on top of a REST / RPC API.~~

May be of interest to look into:

JS client-side, no-database solutions:
* [Horizon](https://horizon.io/)
* [Hood.ie](http://hood.ie/)

Other blockchains:
* [Blockchain.info](https://blockchain.info/api)
* [Ripple](https://ripple.com/build/rippled-apis/)
* Hyperledger
    * https://github.com/hyperledger/fabric/blob/f7b0b5c0a2fc98c898cd1972cc18c811d42c355e/docs/API/CoreAPI.md
  * http://intelledger.github.io/sawtooth_developers_guide/web_api/index.html
  * https://github.com/DigitalAssetCom/hlp-candidate/blob/master/docs/architecture.md

Other databases:
* [Google Cloud Datastore](https://cloud.google.com/datastore/reference/rest/)
* [DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.LowLevelAPI.html)

### Server

* See [related milestone](https://github.com/bigchaindb/bigchaindb/milestone/1)
* [x] Server API: transactions (https://github.com/bigchaindb/bigchaindb/issues/554)
* [x] Server API: transaction status (https://github.com/bigchaindb/bigchaindb/issues/555)

### Driver
* [x] Driver integration tests (https://github.com/bigchaindb/bigchaindb-driver/issues/7)
* [x] Define driver API (https://github.com/bigchaindb/bigchaindb-driver/issues/8)
* [x] Remove driver dependencies on server (https://github.com/bigchaindb/bigchaindb-driver/issues/6)
* [x] Integration transaction model into driver (https://github.com/bigchaindb/bigchaindb-driver/issues/9)
* [x] Implement transaction status (https://github.com/bigchaindb/bigchaindb-driver/issues/10)

## TODO:
* Does the driver need to reimplement the current GET and POST for transactions?

# Targets:

* Finish v1.1 of server API and Python driver by **Thurs, Sept. 1**

**Comment by TimDaub** [comment]
Some potentially interesting endpoints:

- /addresses/<public_key>
- /blocks/
- /blocks/<block_hash>

It's also interesting to discuss how the payload in a transaction should be accessible.

**Comment by sohkai** [comment]
cc @sbellem.

**Comment by diminator** [comment]
I guess I can start specing out some of the known endpoints:
@ttmc @sbellem @sohkai @vrde @r-marques 

## Transactions

### Post a transaction 
```
POST /transactions/
    payload=<TX>

RETURNS
    201 + <ID>
    {4xx, 5xx} + <reason>
``` 
BigchainDB foresees `bigchaindb.write_transaction(tx)` to make the call to the DB

### Retrieve a transaction
```
GET /transactions/<ID>

RETURNS
    200 + <TX> 
    404
```
BigchainDB foresees `bigchaindb.retrieve_transaction(id)` to make the call to the DB

#### Questions (@ttmc @sbellem @sohkai @vrde @r-marques): 

- does the call only looks to the `bigchain` blocks or also in `backlog`?
- does it also look into `bigchain` blocks that are `UNDECIDED`? 

### Retrieve status of a transaction
```
GET /transactions/<ID>/status

RETURNS
    200 + <options: UNDECIDED, DECIDED_VALID, ...>
    404
```

This call will retrieve the status of a transaction. The status can be:
- `404`: the item not found in `backlog | bigchain.{UNDECIDED | DECIDED_VALID}`
- `200` + `UNDECIDED`: the item was found in `backlog | bigchain.UNDECIDED`
- `200` + `DECIDED_VALID`: the item was found in `bigchain.DECIDED_VALID`

**note**: blocks that are marked as `bigchain.DECIDED_INVALID` are excluded from **_every_** query

**Comment by r-marques** [comment]
Should `GET /transaction/<ID>` also return the status?
Right now when you get a transaction and the transaction is on the `bigchain` table you still don't know if the transaction was decided valid or is simply undecided.

`GET /transaction/<ID>/status` would still be helpful for polling since it reduces the amount of data going back and forth.

**Comment by diminator** [comment]
> Should GET /transaction/<ID> also return the status?
> Right now when you get a transaction and the transaction is on the bigchain table you still don't know if the transaction was decided valid or is simply undecided.

The `GET /transaction/<ID>` only returns transactions that are `VALID` and in `bigchain` as they use the `bigchaind.get_transaction(txid)` routine

**Comment by r-marques** [comment]
`bigchaindb.get_transaction` also returns the transaction if its on an undecided state https://github.com/bigchaindb/bigchaindb/issues/555#issuecomment-240138207

**Comment by sohkai** [comment]
@r-marques @diminator @sbellem 

I had a thought about a `/assets/<ID>` endpoint (whose only operation is GET), somewhat related to COALA IP. It'd provide a higher-level endpoint than just `/transactions/<ID>`, and you would give it the ID of the creation transaction that created the asset. Ideally it'd return the asset's data (from the new asset model), plus some number of things such as current owner, list of updates, etc that might be convenient in the future.

Any thoughts? I think it's more semantically clear than always using `/transactions/`; you can still use that, but it seems awkward to use it when we really mean we want to get an asset vs. a transaction (in COALA IP, we link together a number of assets; using a `/transactions/<ID>` URL in those links feels awkward). In addition, since we could add more than just the raw transaction, it may also provide a better experience in the future when we do support things like updatability and refillability.

**Comment by ttmc** [comment]
The proposed digital asset model has an id (UUID) for each asset; see issue #125

**Comment by r-marques** [comment]
I had proposed building an higher level api where instead of dealing with transaction you would deal only with digital assets. That endpoint would be a good example

**Comment by diminator** [comment]
so, compared to `/transactions/ID`,  `/assets/ID` relates to the entire audit trail/provenance?

**Comment by sohkai** [comment]
@diminator I think that it should at least give back the "current state" of the asset, but, if we did want to show the entire audit trail / provenance of the asset, we need to think about a good way to represent this (e.g. a paginated list of transaction IDs).

In any case, maybe this discussion should be moved off to another issue, e.g. Client API v1.2?

**Comment by diminator** [comment]
> In any case, maybe this discussion should be moved off to another issue, e.g. Client API v1.2?

agreed

**Comment by ttmc** [comment]
@r-marques said he would create a new issue for the digital asset endpoint(s).

**Comment by sbellem** [comment]
@diminator regarding the trailing slash:

From the point of view of writing a client, it's actually quite inconvenient to have some urls requiring the trailing slash, meanwhile others requiring NOT to have it.

I suggest that the server is flexible, and can handle both cases no matter what the url is.

**Comment by sohkai** [comment]
@ttmc I think we can close this once we push out the new version of BigchainDB this week :).

**Comment by ttmc** [comment]
The new version of BigchainDB (0.6.0) was pushed out yesterday, so I'm going to close this issue now, as suggested by @sohkai: https://github.com/bigchaindb/bigchaindb/issues/362#issuecomment-243056961
