### ISSUE TITLE
Make cloud deployment starter templates for AWS & Azure

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#498]
- [x] Initial production node architecture design, documentation & review - Issue #492
- [x] Test & review the Azure deployment template we got from Microsoft - Issue #503
- [x] Research & test some provisioning & config. mgmt. tools. Test on AWS. Documentation. - Issue #511
- [x] Revise docs to prep. for new section on prod. node setup & management - Issue #533
- [x] Documentation Revisions - Pull request #539 
- [x] Python scripts to provision minimal production node on AWS - Issue #540
- [x] Minimal Ansible thing to install, configure & run an NTP daemon - Issue #551
- [x] Minimal Ansible thing to setup filesystem/storage for RethinkDB - Issue #552
- [x] Minimal Ansible thing to install RethinkDB & BigchainDB - Issue #553
- [x] Test new Azure deployment template from MS
- [x] Submit pull request to Azure/azure-quickstart-templates. See https://github.com/Azure/azure-quickstart-templates/pull/2543 
- [ ] Once the above PR is approved and merged, add Azure deployment docs to our docs - PR #705 

Note: This Project-Issue started out as "Production Node Deployment & Management" but that was too vague and had no clear endpoint.
