### ISSUE TITLE
Project: Renaming things for clarity, consistency, and correctness

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#756]
There is a small cluster of issues around renaming things for clarity, consistency, and correctness. I thought it might be useful to bundle them all together for reference:
- [x] #746 - Naming convention: public/private keys versus verifying/signing keys?
- [x] #743 - Replace the notions of inputs and outputs with fulfillments and conditions
- [x] #717 - Rename `data_id` in the Metadata and Asset models
- [x] #715 - Revisit `to_hash()` in Assets and Metadata
- [x] #709 - Sanitize naming/positioning of fulfillments, conditions, inputs, outputs
- [x] #708 - Why use "id" and "data_id" for the same thing?
- [x] #679 - Rename variable "validity" to more descriptive name, such as "block_statuses"
- [x] #626 - Rename 'owners_after' to 'fulfillers'
- [ ] #603 - rename `get_owned_ids` to `get_unspents`

Others?

**Comment by ttmc** [comment]
There's only one open issue on this list and it can live on its own, so I'm closing this issue (which is just a list of other issues).
