### ISSUE TITLE
BigchainDB Transaction Schema Upgrade Plan

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#850]
Issues based on [milestone](https://github.com/bigchaindb/bigchaindb/milestone/5).

**Meeting date**: Monday, Nov. 28 1pm - 3pm

----------------------

**Tasks**:

- [x] #852 - Is metadata.id necessary?
- [x] #841 - Remove divisible keyword
- [x] #838 - Condition.cid and Fulfillment.fid should always be necessary or never necessary
- [x] #828 Revisit "inner" transaction dict
- [x] #743 Replace notions of inputs and outputs with fulfillments and conditions
- [x] #710 - CREATE transaction should support multiple owners in implicit condition
- [x] #709 - Sanitize naming/positioning of fulfillments, conditions, inputs, and outputs
- [x] #697 - Use transaction ID as asset ID
- [x] ~~#339 - Transaction malleability of transactions containing no signatures~~ Unrelated to current upgrade

----------------------

For reference, the current pieces of the Transaction model (you can see a [JSON Schema version of this](https://github.com/bigchaindb/bigchaindb/blob/schema-definition/bigchaindb/common/schema/transaction.yaml)):

**Transaction**:

```js
tx = {
    "id": "<SHA3 digest of the transaction>",
    "version": "<Transaction schema version>",
    "transaction": {
        "operation": "<One of CREATE, TRANSFER, GENESIS>",
        "timestamp": "<User / client provided timestamp of the transaction>",
        "conditions": [<condition>, ...],
        "fulfillments": [<fulfillment>, ...],
        "metadata": <metadata>,
        "asset": <asset>
    }
}
```

An example:

```js
"transaction": {
    "id": "933cd83a419d2735822a2154c84176a2f419cbd449a74b94e592ab807af23861",
    "version": 1,
    "transaction": {
        "operation": "CREATE",
        "timestamp": "1460981667"
        "conditions": [...],
        "fulfillments": [...],
        "metadata": ...,
        "asset": ...
    }
}
```

**Conditions**:

```js
condition = {
    "cid": <Index of condition in transaction, must be a whole number>,
    "amount": <Whole number representing divisible amounts>,
    "owners_after": ["<Base58 public key>", ...],
    "condition": {
        "uri": "<Condition URI>",
        "details": <A dict representing the fulfillment that generated this condition>
    }
}
```

A single signature example:

```js
"conditions": [
    {
        "cid": 0,
        "amount": 1,
        "owners_after": [
            "BwuhqQX8FPsmqYiRV2CSZYWWsSWgSSQQFHjqxKEuqkPs"
        ],
        "condition": {
            "uri": "cc:4:20:oqXTWvR3afHHX8OaOO84kZxS6nH4GEBXD4Vw8Mc5iBo:96",
            "details":  {
                "bitmask": 32,
                "public_key": "BwuhqQX8FPsmqYiRV2CSZYWWsSWgSSQQFHjqxKEuqkPs",
                "signature": None,
                "type": "fulfillment",
                "type_id": 4
            }
        }
    }
]
```

A threshold condition example:

```js
"conditions": [
    {
        "cid": 0,
        "amount": 1,
        "owners_after": [
            "8NaGq26YMcEvj8Sc5MnqspKzFTQd1eZBAuuPDw4ERHpz",
            "ALE9Agojob28D1fHWCxFXJwpqrYPkcsUs26YksBVj27z",
            "Cx4jWSGci7fw6z5QyeApCijbwnMpyuhp4C1kzuFc3XrM"
        ],
        "condition": {
            "uri": "cc: 2: 29: FoElId4TE5TU2loonT7sayXhxwcmaJVoCeIduh56Dxw: 246",
            "details": {
                "bitmask": 41,
                "subfulfillments": [
                    {
                        "bitmask": 32,
                        "public_key": "8NaGq26YMcEvj8Sc5MnqspKzFTQd1eZBAuuPDw4ERHpz",
                        "signature": None,
                        "type": "fulfillment",
                        "type_id": 4,
                        "weight": 1
                    },
                    {
                        "bitmask": 32,
                        "public_key": "ALE9Agojob28D1fHWCxFXJwpqrYPkcsUs26YksBVj27z",
                        "signature": None,
                        "type": "fulfillment",
                        "type_id": 4,
                        "weight": 1
                    },
                    {
                        "bitmask": 32,
                        "public_key": "Cx4jWSGci7fw6z5QyeApCijbwnMpyuhp4C1kzuFc3XrM",
                        "signature": None,
                        "type": "fulfillment",
                        "type_id": 4,
                        "weight": 1
                    }
                ],
                "threshold": 2,
                "type": "fulfillment",
                "type_id": 2
            }
        }
    }
]
```

**Fulfillments**:

```js
fulfillment = {
    "fid": <Index of fulfillment in unspent transaction, must be a whole number>,
    "owners_before": ["<Base58 public key>", ...],
    "fulfillment": <A fulfillment URI or the details of an unsigned fulfillment>,
    "input": { // or null
        "cid": <Condition index>,
        "txid": "<SHA3 digest of unspent transaction>"
    }
}
```

An example:

```js
"fulfillments": [
    {
        "fid": 0,
        "owners_before": [
            "BwuhqQX8FPsmqYiRV2CSZYWWsSWgSSQQFHjqxKEuqkPs"
        ],
        "fulfillment": "cf:4:oqXTWvR3afHHX8OaOO84kZxS6nH4GEBXD4Vw8Mc5iBqzkVR6cFJhRvMGKa-Lc81sdYWVu0ZSMPGht-P7s6FZLkRXDqrwwInabLhjx14eABY34oHb6IyWcB-dyQnlVNEI",
        "input": {
            "cid": 0,
            "txid": "933cd83a419d2735822a2154c84176a2f419cbd449a74b94e592ab807af23861"
        }
    }
]
```

**Metadata**:

```js
metadata = { // or null
    "id": "<UUID4>",
    "data": <Arbitrary JSON>
}
```

An example:

```js
"metadata": {
    "id": "d6a3b850-e960-4391-98c3-f16f1cd26a40",
    "data": {}
}
```

**Asset**:

```js
asset = {
    "id": "<UUID4>",
    "divisible": <boolean>,
    "updatable": <boolean>,
    "refillable": <boolean>,
    "data": <Arbitrary JSON or null>
}
```

An example:

```js
"asset": {
    "id": "8409a700-0929-4143-ae3c-f9b7d6c3c2a6",
    "divisible": False,
    "updatable": False,
    "refillable": False,
    "data": {
        "msg": "Hello BigchainDB!"
    }
}
```

----------------------

### #852 - Is metadata.id necessary? (PR: #856)

By @libscott 

**Proposes**: Remove the `id` property from the metadata (and then flattening `data`), as there's a 1:1 mapping between metadata and transactions. Do we want to index by metadata? Do we envision searches for transactions by metadata details?

**Model change**:

```js
metadata = {
+   <Arbitrary JSON>
-   "id": "<UUID4>",
-   "data": <Arbitrary JSON>
}
```

**Status**: Approved (Ambiguous with TXID)

### #841 - Remove divisible keyword

By @libscott

**Proposes**: Remove the `divisible` property from the asset, as it may not be necessary. `amount: 1` may cover non-divisible assets, but what about refillable assets that start at 1?

**Model change**:

```js
asset = {
    "id": "<UUID4>",
-   "divisible": <boolean>,
    "updatable": <boolean>,
    "refillable": <boolean>,
    "data": <Arbitrary JSON or null>
}
```

**Status**:

- [x] Approve (Redundant if well documented)
- [ ] Requires changes
- [ ] Investigate
- [ ] Defer

### #838 - Condition.cid and Fulfillment.fid should always be necessary or never necessary

By @libscott

**Proposes**: Enforcing `cid` and `fid` to be either mandatory or non-present. Are we able to trust databases (and binary format serializations) to maintain ordering in a json blob?

**Model changes**:

```js
condition = {
-   "cid": <Index of condition in transaction, must be a whole number>,
    "amount": <Whole number representing divisible amounts>,
    "owners_after": ["<Base58 public key>", ...],
    "condition": {
        "uri": "<Condition URI>",
        "details": <A dict representing the fulfillment that generated this condition>
    }
}

fulfillment = {
-   "fid": <Index of fulfillment in unspent transaction, must be a whole number>,
    "owners_before": ["<Base58 public key>", ...],
    "fulfillment": <A fulfillment URI or the details of an unsigned fulfillment>,
    "input": { // or null
        "cid": <Condition index>,
        "txid": "<SHA3 digest of unspent transaction>"
    }
}
```

**Status**: Approved (redundant if array order respected)

### #828 Revisit "inner" transaction dict (PR: #855)

By @sohkai

**Proposes**: Remove the inner `transaction` dict from the model. Might make it harder to determine what gets hashed, but our current hashing implementation doesn't use this inner dict anyway. The `version` is included in what gets hashed.

**Model changes**:

```js
tx = {
    "id": "<SHA3 digest of the transaction>",
    "version": "<Transaction schema version>",

+   "operation": "<One of CREATE, TRANSFER, GENESIS>",
+   "timestamp": "<User / client provided timestamp of the transaction>",
+   "conditions": [<condition>, ...],
+   "fulfillments": [<fulfillment>, ...],
+   "metadata": <metadata>,
+   "asset": <asset>

-   "transaction": {
-       "operation": "<One of CREATE, TRANSFER, GENESIS>",
-       "timestamp": "<User / client provided timestamp of the transaction>",
-       "conditions": [<condition>, ...],
-       "fulfillments": [<fulfillment>, ...],
-       "metadata": <metadata>,
-       "asset": <asset>
-   }
}
```

**Status**: Approved (signatures not outside)

### #743 Replace notions of inputs and outputs with fulfillments and conditions

Proposed by @r-marques and issue created by @ttmc

**Proposes**: Lots of changes. Can we remove `Condition.details` (do we need subfillment structures)? Use `parties` instead of `public_keys`?

**Model changes**:

```js
condition = {
    "cid": <Index of condition in transaction, must be a whole number>,
    "amount": <Whole number representing divisible amounts>,

+   "public_keys": ["<Base58 public key>", ...],
+   "uri": "<Condition URI>",

-   "owners_after": ["<Base58 public key>", ...],
-   "condition": {
-       "uri": "<Condition URI>",
-       "details": <A dict representing the fulfillment that generated this condition>
-   }
}

fulfillment = {
    "fid": <Index of fulfillment in unspent transaction, must be a whole number>,
    "fulfillment": <A fulfillment URI or the details of an unsigned fulfillment>,

+   "public_keys": ["<Base58 public key>", ...],
-   "owners_before": ["<Base58 public key>", ...],


+   "fulfills": {
-   "input": {
        "cid": <Condition index>,
        "txid": "<SHA3 digest of unspent transaction>"
    }
}
```

**Status**: Requires changes (see: #875)

### #710 - CREATE transaction should support multiple owners in implicit condition

By @TimDaub

**Proposes**: Multiple "issuers" should be supported when creating an asset. No model changes, but does require changes in the logic for creating and validating a CREATE transaction.

**Status**: Requires changes (resolved in #794)

### #709 - Sanitize naming/positioning of fulfillments, conditions, inputs, and outputs

By @TimDaub

**Proposes**: Could `conditions` and `fulfillments` be renamed to `inputs` or `outputs`? Does that work with Interledger? Could a fulfillment URI be stored outside of the transaction body?

**Model changes**:

```js
tx = {
    "id": "<SHA3 digest of the transaction>",
    "version": "<Transaction schema version>",
    "transaction": {
        "operation": "<One of CREATE, TRANSFER, GENESIS>",
        "timestamp": "<User / client provided timestamp of the transaction>",

+       "inputs": [<condition>, ...],
+       "outputs": [<fulfillment>, ...],
-       "conditions": [<condition>, ...],
-       "fulfillments": [<fulfillment>, ...],

        "metadata": <metadata>,
        "asset": <asset>
    }
}
```

**Status**: Requires changes (see: #875)

### #697 - Use transaction ID as asset ID

By @libscott

**Proposes**: Remove asset IDs and use the CREATE transaction as the asset's ID. What if two transactions have the same ID? Can you, or is it important to, always generate unique IDs? How do you separate asset indices from transaction indices? Should we include signatures in the CREATE transaction, to ensure that the transaction hash is secure?

**Model changes**:

```js
asset = {
-   "id": "<UUID4>",
    "divisible": <boolean>,
    "updatable": <boolean>,
    "refillable": <boolean>,
    "data": <Arbitrary JSON or null>
}
```

**Status**: Approved (Is simple, more asset changes will likely follow but this will be Good Enough for now)

### #339 - Transaction malleability of transactions containing no signatures

By @ttmc

**Proposes**: Transactions that don't include any signatures (e.g. transactions with only hashlock or timelock conditions) are malleable. Maybe include the transaction data in the hash? Maybe add a submitter public key and signature to the model? Maybe tell users to always include at least one signature condition? Maybe this isn't a problem, because crypto-conditions are agnostic about requiring signatures?

**Status**: Investigate (Actually not part of TX schema, it's a detail of crypto conditions)

**Comment by sohkai** [comment]
Closing with https://github.com/bigchaindb/bigchaindb/milestone/5 being complete.
